# Generated by Django 2.0.4 on 2018-04-03 21:19

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields
import wagtailstreamforms.blocks


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntroPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('body', wagtail.core.fields.StreamField((('section', wagtail.core.blocks.StructBlock((('id', wagtail.core.blocks.CharBlock(help_text='HTML id of element', max_length=250, required=False)), ('header', wagtail.core.blocks.StructBlock((('header_icon', wagtail.core.blocks.CharBlock(max_length=50, required=False)), ('header_text', wagtail.core.blocks.CharBlock(max_length=250))))), ('dark', wagtail.core.blocks.BooleanBlock(help_text='Toggle the dark background variant', required=False)), ('body', wagtail.core.blocks.StreamBlock((('richtext', wagtail.core.blocks.RichTextBlock()), ('html', wagtail.core.blocks.RawHTMLBlock()), ('panel', wagtail.core.blocks.StructBlock((('header', wagtail.core.blocks.StructBlock((('header_icon', wagtail.core.blocks.CharBlock(max_length=50, required=False)), ('header_text', wagtail.core.blocks.CharBlock(max_length=250))))), ('body', wagtail.core.blocks.RichTextBlock()), ('footer', wagtail.core.blocks.StructBlock((('alignment', wagtail.core.blocks.ChoiceBlock(choices=[('', 'Default'), ('centered', 'Centered')], required=False)), ('buttons', wagtail.core.blocks.StreamBlock((('button', wagtail.core.blocks.StructBlock((('button_icon', wagtail.core.blocks.CharBlock(max_length=50, required=False)), ('button_class', wagtail.core.blocks.CharBlock(help_text='Extra css classes to add to button', max_length=200, required=False)), ('button_page', wagtail.core.blocks.PageChooserBlock(required=False)), ('button_url', wagtail.core.blocks.URLBlock(required=False)), ('button_text', wagtail.core.blocks.CharBlock(max_length=250))))),), required=False)))))))), ('twopane', wagtail.core.blocks.StructBlock((('panel_alignment', wagtail.core.blocks.ChoiceBlock(choices=[('left', 'Left'), ('right', 'Right')])), ('content_pane', wagtail.core.blocks.RichTextBlock()), ('panel_pane', wagtail.core.blocks.StructBlock((('header', wagtail.core.blocks.StructBlock((('header_icon', wagtail.core.blocks.CharBlock(max_length=50, required=False)), ('header_text', wagtail.core.blocks.CharBlock(max_length=250))))), ('body', wagtail.core.blocks.RichTextBlock()), ('footer', wagtail.core.blocks.StructBlock((('alignment', wagtail.core.blocks.ChoiceBlock(choices=[('', 'Default'), ('centered', 'Centered')], required=False)), ('buttons', wagtail.core.blocks.StreamBlock((('button', wagtail.core.blocks.StructBlock((('button_icon', wagtail.core.blocks.CharBlock(max_length=50, required=False)), ('button_class', wagtail.core.blocks.CharBlock(help_text='Extra css classes to add to button', max_length=200, required=False)), ('button_page', wagtail.core.blocks.PageChooserBlock(required=False)), ('button_url', wagtail.core.blocks.URLBlock(required=False)), ('button_text', wagtail.core.blocks.CharBlock(max_length=250))))),), required=False))))))))))), ('form', wagtail.core.blocks.StructBlock((('form', wagtailstreamforms.blocks.FormChooserBlock()), ('form_action', wagtail.core.blocks.CharBlock(help_text='The form post action. "" or "." for the current page or a url', required=False)), ('form_reference', wagtailstreamforms.blocks.InfoBlock(help_text='This form will be given a unique reference once saved', required=False))))))))))),))),
                ('intro_header', models.CharField(max_length=100)),
                ('intro_sub_header', models.CharField(blank=True, max_length=250, null=True)),
                ('intro_button_icon', models.CharField(blank=True, max_length=50, null=True)),
                ('intro_button_text', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='NavigationItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('icon', models.CharField(max_length=50)),
                ('text', models.CharField(max_length=250)),
                ('page_anchor', models.CharField(blank=True, max_length=50, null=True)),
                ('external_url', models.URLField(blank=True, null=True)),
                ('page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
