# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-25 07:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import resume.blocks
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.snippets.blocks


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('objective_header', models.CharField(default='Objective', max_length=150)),
                ('objective', wagtail.core.fields.RichTextField()),
                ('skills', wagtail.core.fields.StreamField((('skill_set', wagtail.core.blocks.StructBlock((('header', wagtail.core.blocks.CharBlock(max_length=150)), ('skills', wagtail.core.blocks.ListBlock(wagtail.snippets.blocks.SnippetChooserBlock('resume.ResumeSkill')))))),))),
                ('body', wagtail.core.fields.StreamField((('education', wagtail.core.blocks.StructBlock((('header', wagtail.core.blocks.CharBlock(max_length=200)), ('education', wagtail.core.blocks.ListBlock(resume.blocks.ResumeEducationBlock))))), ('experience', wagtail.core.blocks.StructBlock((('header', wagtail.core.blocks.CharBlock(max_length=200)), ('experience', wagtail.core.blocks.ListBlock(resume.blocks.ResumeExperienceBlock)))))))),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ResumeSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
                ('url', models.URLField(blank=True, max_length=500, null=True)),
                ('description', wagtail.core.fields.RichTextField(blank=True, null=True)),
            ],
        ),
    ]
