# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-25 20:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumepage',
            name='skills_header',
            field=models.CharField(default='Professional Skills', max_length=100),
        ),
    ]
